# Welcome to Nubia Jekyll Theme!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

theme_version: 1.0.4

# Site settings
lang: es_ES
title: Bridge
name: Chiven Young
title_home: Chiven Young
logo: # Logo image URL
description: Escriba una descripción
baseurl: '' # The subpath of your site, e.g. /blog
url: 'https://chiven-young.github.io/' # The base hostname & protocol for your site

# twitter:
  username: hiven-young

# facebook: hiven-young

instagram: bridgegrowing

github: chiven-young

markdown: kramdown
highlighter: rouge
permalink: /:title
paginate: 11

plugins:
  - jekyll-paginate
  - jekyll/tagging
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

include:
  - _pages
  - _redirects
  - .well-known

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

# SCSS Config
sass:
  style: compressed # possible values: nested expanded compact compressed

# SiteMap Plugin
# defaults:
#   - scope:
#       path: 'tag'
#     values:
#       sitemap: false

# Jekyll Feed Plugin
feed:
  categories:
  - aplicaciones
  - desarrollo-web
  - internet

# Jekyll seo tag config
facebook:
  app_id: add your app id

# Tags
tag_page_dir: tag
tag_page_layout: tag_page
tag_permalink_style: pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  leninalbertop:
    name: Chiven Young
    bio: Escriba una descripción.
    gravatar: https://randomuser.me/api/portraits/men/93.jpg
    picture: https://randomuser.me/api/portraits/men/93.jpg
    email: chiven@yeah.net
    # facebook: chiven-young
    github: chiven-young
    # twitter: chiven-young
    # pinterest: chiven-young
